spring:
  datasource:
    url: ${TEST_DB_URL:jdbc:postgresql://localhost:5433/hrms_test}
    username: ${TEST_DB_USERNAME:postgres}
    password: ${TEST_DB_PASSWORD:admin@123}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    validate-on-migrate: true
    clean-disabled: false

  sql:
    init:
      mode: never